export const TEMPLATES = [
  {
    id: 'modern-blue',
    name: 'Modern ',
    description: 'A bold sidebar layout with a confident indigo accent. Great all-rounder.',
    tags: ['Popular', 'Two-column'],
    defaultColor: '#4f46e5',
    defaultSecondary: '#171923',
    defaultFont: 'Inter',
  },
  {
    id: 'ats-professional',
    name: 'ATS Pro',
    description: 'A vivid header band and playful accents for design & marketing roles.',
    tags: ['Bold'],
    defaultColor: '#ea580c',
    defaultSecondary: '#1e1b4b',
    defaultFont: 'Poppins'
  },
  {
    id: 'creative',
    name: 'Fresh',
    description: 'A vivid header band and playful accents for design & marketing roles.',
    tags: ['Bold'],
    defaultColor: '#ea580c',
    defaultSecondary: '#1e1b4b',
    defaultFont: 'Poppins',
  },
  {
    id: 'minimal',
    name: 'Clean',
    description: 'Generous whitespace and quiet typography. Lets your experience do the talking.',
    tags: ['Minimal'],
    defaultColor: '#111827',
    defaultSecondary: '#111827',
    defaultFont: 'Inter',
  },
  {
    id: 'elegant',
    name: 'Elegant',
    description: 'Serif headings and a refined rule-line layout for senior & academic roles.',
    tags: ['Serif'],
    defaultColor: '#7c2d12',
    defaultSecondary: '#7c2d12',
    defaultFont: 'Playfair Display',
  },
  {
    id: 'corporate',
    name: 'Corporate',
    description: 'Structured header bar and clean grids — a safe, formal choice.',
    tags: ['Formal'],
    defaultColor: '#0f4c81',
    defaultSecondary: '#0b2540',
    defaultFont: 'Lato',
  },
  {
    id: 'fresher',
    name: 'Fresher',
    description: 'Friendly and skills-forward — designed for first jobs & internships.',
    tags: ['Entry-level'],
    defaultColor: '#0d9488',
    defaultSecondary: '#0d9488',
    defaultFont: 'Poppins',
  },
  {
    id: 'executive',
    name: 'Executive',
    description: 'A dark, premium header for leadership and C-suite profiles.',
    tags: ['Premium'],
    defaultColor: '#b08d57',
    defaultSecondary: '#0b0c10',
    defaultFont: 'Merriweather',
  },
];

export const getTemplateMeta = (id) => TEMPLATES.find((t) => t.id === id) || TEMPLATES[0];
